either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls'))
]

questions/urls.py
from django.urls import path
from . import views

app_name = "questions"

urlpatterns = [
    path('', views.index, name="index"),
    # Create
    path('question-create/', views.question_create, name="question_create"),
    path('<int:question_id>/detail/<int:choice_id>/', views.detail, name="detail"),
    path('<int:question_id>/pick-count/<int:pick_num>/', views.pick_count, name="pick_count"),
    path('<int:question_id>/answer-create/<int:choice_id>/', views.answer_create, name="answer_create"),
    # Update
    path('<int:question_id>/question-update/', views.question_update, name="question_update"),
    # Delete
    path('<int:question_id>/question-delete/', views.question_delete, name="question_delete"),
    path('<int:question_id>/answer-delete/<int:choice_id>/', views.answer_delete, name="answer_delete"),
]

questions/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=50)
    option_left = models.CharField(max_length=50)
    option_right = models.CharField(max_length=50)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment = models.TextField()

questions/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice
import random

# Create your views here.
def index(request):
    questions = Question.objects.all()
    question_ids = []
    for question in questions:
        question_ids.append(question.id)
    q_id = random.choice(question_ids)
    question = Question.objects.get(id=q_id)
    choices = question.choice_set.all()
    context = {
        'question': question,
        'choices' : choices,
    }
    return render(request, 'index.html', context)

def question_create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        option_left = request.POST.get('option-left')
        option_right = request.POST.get('option-right')

        Question.objects.create(
            title = title,
            option_left = option_left,
            option_right = option_right,
        )
        return redirect('questions:index')
    else:
        return render(request, 'form.html')

def detail(request, question_id, choice_id):
    question = Question.objects.get(id=question_id)
    choices = question.choice_set.all()
    left = 0
    for choice in choices:
        if choice.pick == 1:
            left += 1
    total = len(choices)
    right = total - left
    left_per = round(left / total * 100, 1)
    right_per = round(right / total * 100, 1)
    choice = Choice.objects.get(id=choice_id)
    context = {
        'question': question,
        'left': left,
        'right': right,
        'left_per': left_per,
        'right_per': right_per,
        'choice': choice,
        'choices': choices,
    }
    return render(request, 'detail.html', context)

def pick_count(request, question_id, pick_num):
    question = Question.objects.get(id=question_id)
    pick_num = pick_num
    choice = Choice.objects.create(
        question = question,
        pick = pick_num,
    )
    return redirect('questions:detail', question_id, choice.id)

def answer_create(request, question_id, choice_id):
    choice = Choice.objects.get(id=choice_id)
    comment = request.POST.get('comment')
    choice.comment = comment
    choice.save()
    return redirect('questions:detail', question_id, choice_id)

def question_update(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        title = request.POST.get('title')
        option_left = request.POST.get('option-left')
        option_right = request.POST.get('option-right')

        question.title = title
        question.option_left = option_left
        question.option_right = option_right
        question.save()
        return redirect('questions:index')
    else:
        context = {
            'question': question,
        }
        return render(request, 'question_edit.html', context)

def question_delete(request, question_id):
    question = Question.objects.get(id=question_id)
    question.delete()
    return redirect('questions:index')

def answer_delete(request, question_id, choice_id):
    choice_del = Choice.objects.get(id=choice_id)
    choice_del.delete()
    question = Question.objects.get(id=question_id)
    choice_ids = []
    choices = question.choice_set.all()
    for choice_pick in choices:
        choice_ids.append(choice_pick.id)
    c_id = random.choice(choice_ids)
    return redirect('questions:detail', question_id, c_id)

questions/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
      @font-face { font-family: 'HangeulNuri-Bold'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_three@1.0/HangeulNuri-Bold.woff') format('woff'); font-weight: normal; font-style: normal; }
      @font-face { font-family: 'BMHANNAAir'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.0/BMHANNAAir.woff') format('woff'); font-weight: normal; font-style: normal; }
      @font-face { font-family: 'TDTDTadakTadak'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.0/TDTDTadakTadak.woff') format('woff'); font-weight: normal; font-style: normal; }
      <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/moonspam/NanumSquare/master/nanumsquare.css"> .nanumsquare { font-family: 'NanumSquare', sans-serif !important; }
      .navbar {
        font-family: 'HangeulNuri-Bold';
      }

      .title {
        font-family: 'BMHANNAAir';
      }

      .options {
        font-family: 'TDTDTadakTadak';
      }

      h5 {
        font-size: 40px;
      }

      .answer {
        font-family: 'NanumSquare', sans-serif;
      }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'questions:index' %}">랜덤 질문</a>
    <a class="navbar-brand" href="{% url 'questions:question_create' %}">질문 등록</a>
  </nav>
  <!-- <a href="{% url 'questions:index' %}">랜덤 질문</a>
  <a href="{% url 'questions:question_create' %}">질문 등록</a> -->
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

questions/templates/detail.html
{% extends 'base.html' %}
{% block body %}
  <h1 class="d-flex justify-content-center m-3 title">{{question.title}}</h1>
  <div class="container">
    <div class="row">
      <a style="height: 300px;" class="btn btn-info text-white d-flex flex-column justify-content-center col-6 options">
        <h5>{{question.option_left}}</h5>
        <h5>{{left}}명</h5>
        <h5>{{left_per}}%</h5>
      </a>
      <a class="btn btn-warning text-white d-flex flex-column justify-content-center col-6 options">
        <h5>{{question.option_right}}</h5>
        <h5>{{right}}명</h5>
        <h5>{{right_per}}%</h5>
      </a>
    </div>
  </div>
  <div class="container mt-5">
    <form action="{% url 'questions:answer_create' question.id choice.id %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="comment">댓글 입력</label>
        <input type="text" class="form-control" id="comment" name="comment">
      </div>
    </form>
    <table class="table">
      <tbody>
        {% for choice_pick in choices %}
        {% if choice_pick.comment %}
        <tr>
          <td class="answer">{{choice_pick.comment}}</td>
          <td><a class="btn btn-dark" href="{% url 'questions:answer_delete' question.id choice_pick.id %}">댓글 삭제</a></td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

questions/templates/form.html
{% extends 'base.html' %}
{% block body %}
  <form class="m-5" action=""  method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">제목</label>
      <input type="text" class="form-control" id="title" name="title" placeholder="제목">
    </div>
    <div class="form-group">
      <label for="option-left">선택1</label>
      <input type="text" class="form-control" id="option-left" name="option-left" placeholder="선택1">
    </div>
    <div class="form-group">
      <label for="option-right">선택2</label>
      <input type="text" class="form-control" id="option-right" name="option-right" placeholder="선택2">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

questions/templates/index.html
{% extends 'base.html' %}
{% block body %}
  <h1 class="d-flex justify-content-center m-3 title">{{question.title}}</h1>
  <div class="container">
    <div class="row">
      <a style="height: 300px;" class="btn btn-info text-white d-flex flex-column justify-content-center col-6 options" href="{% url 'questions:pick_count' question.id 1 %}">
        <h5>{{question.option_left}}</h5>
      </a>
      <a class="btn btn-warning text-white d-flex flex-column justify-content-center col-6 options" href="{% url 'questions:pick_count' question.id 2 %}">
          <h5>{{question.option_right}}</h5>
      </a>
    </div>
    </div>
      <a class="btn btn-secondary mt-3" href="{% url 'questions:question_update' question.id %}">질문 수정</a>
      <a class="btn btn-danger mt-3" href="{% url 'questions:question_delete' question.id %}">질문 삭제</a>
    </div>
  </div>
  <div class="container mt-5">
    <table class="table">
      <tbody>
        {% for choice_pick in choices %}
        {% if choice_pick.comment %}
        <tr>
          <td class="answer">{{choice_pick.comment}}</td>
          <td><a class="btn btn-dark" href="{% url 'questions:answer_delete' question.id choice_pick.id %}">댓글 삭제</a></td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

questions/templates/question_edit.html
{% extends 'base.html' %}
{% block body %}
  <form class="m-5" action=""  method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">제목</label>
        <input type="text" class="form-control" id="title" name="title" value="{{question.title}}">
      </div>
      <div class="form-group">
        <label for="option-left">선택1</label>
        <input type="text" class="form-control" id="option-left" name="option-left" value="{{question.option_left}}">
      </div>
      <div class="form-group">
        <label for="option-right">선택2</label>
        <input type="text" class="form-control" id="option-right" name="option-right" value="{{question.option_right}}">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}